# Task 1: Predict Employed/Not employed

### Import data, a bit of EDA

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline

In [35]:
df=pd.read_excel('UCT_Data.xlsx')
df

,YEAR,CAMPUSID,MAINACTIVITY,EMPLOYER,JOBTITLE,INDUSTRY,SALARY,SECTOR,EMPLOYMENT RELATED TO STUDIES,StudentData.Sex,...,StudentData.Degree Academic Career Code,StudentData.Degree Academic Career,StudentData.Degree Faculty Code,StudentData.Degree Faculty,StudentData.Awarded Degree Code,StudentData.Awarded Degree,StudentData.Academic Program Code,StudentData.Academic Program,StudentData.Academic Plan 1,StudentData.Academic Plan 1 Code
0,2013,ADLSIM001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Political Studies,HB001POL01
1,2013,ALLMIC013,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Economics,HB001ECO01
2,2013,ALXLAR003,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Organisational Psychology,HB001BUS08
3,2013,BLXSIV001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Media & Writing,HB001FAM07
4,2013,BNCAMY001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Gender Studies,HB001AXL01
5,2013,BRCSHA001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Media & Writing,HB001FAM07
6,2013,CRGMIC002,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,History,HB001HST04
7,2013,DVLNIC008,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Psychology,HB001PSY01
8,2013,FRRNIC006,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Gender Studies,HB001AXL01
9,2013,FRRVIC001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Organisational Psychology,HB001BUS08
10,2013,GRRLAR001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Social Anthropology,HB001AXL04
11,2013,GSNAAD001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Organisational Psychology,HB001BUS08
12,2013,HTHVAR001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Gender Studies,HB001AXL01
13,2013,ISCNAS004,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Psychology,HB001PSY01
14,2013,JCKVIC003,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Environmental & Geog Science,HB001EGS02
15,2013,JHNDAN003,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Organisational Psychology,HB001BUS08
16,2013,JLSZAR001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Social Anthropology,HB001AXL04
17,2013,KNGMIC012,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Economics,HB001ECO01
18,2013,KRBKEN001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Organisational Psychology,HB001BUS08
19,2013,KTZREN001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Organisational Psychology,HB001BUS08
20,2013,LBBRAF001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Organisational Psychology,HB001BUS08
21,2013,LNDNIC008,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Gender Studies,HB001AXL01
22,2013,LNRJEN001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Philosophy,HB001PHI01
23,2013,LWNJAN002,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Gender Studies,HB001AXL01
24,2013,MCKDEN004,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Psychology,HB001PSY01
25,2013,ELLELM001,EMPLOYED,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Philosophy,HB001PHI01
26,2013,MNTCAT003,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,History,HB001HST04
27,2013,NDXNIK001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Gender Studies,HB001AXL01
28,2013,ODNREH001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Economics,HB001ECO01
29,2013,OSTLEI001,STUDYING,NaN,NaN,NaN,NaN,NaN,NaN,Female,...,UGRD,Undergraduate,HUM,Humanities,HB02,Bachelor of Social Science,HB001,Bachelor of Social Science,Gender Studies,HB001AXL01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15992,2017,ASPCHS001,EMPLOYED,COGNIA LAW,LEGAL GRADUATE,Legal,R 9001- R 12 000,Private Sector,Somewhat related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15993,2017,ALCRAE001,EMPLOYED,MINE,TRADER,"Finance, Insurance, Actuarial Work",> R 50 000,Private Sector,Somewhat related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15994,2017,CSTMAR019,EMPLOYED,CRUZEIRO DO SUL - REDS SUPERMARKET,HR MANAGET,Commercial & Retail,R 15 001- R 20 000,Private Sector,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15995,2017,MURMCD003,EMPLOYED,SELF,CHIROPRACTOR,Health Care,Ad-Hoc (varies),Private Sector,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15996,2017,MHLREA007,EMPLOYED,RETRO RABBIT,JUNIOR DEVELOPER,"IT, Telecoms & Information Services",R 15 001- R 20 000,Private Sector,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15997,2017,RUSBUR001,EMPLOYED,TMF CORPORATE SERVICES,TAX OFFICER,Business & Management,R 20 001- R 30 000,Private Sector,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15998,2017,LFSTAK001,EMPLOYED,ZITHULELE HOSPITAL,COMMUNITY SERVICE AUDIOLOGIST,Health Care,R 15 001- R 20 000,Government,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15999,2017,TRLJOH001,EMPLOYED,SELF,PSYCHIATRIST,Health Care,Ad-Hoc (varies),Private Sector,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16000,2017,MILKAT012,EMPLOYED,NaN,NaN,OTHER,R 9001- R 12 000,"Education, Non-government",Not related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16001,2017,KTSMAL001,EMPLOYED,AFRICAN DEBT ADVISORS,SALES,OTHER,R 5001- R 7000,Private Sector,Not related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16002,2017,MDRPAT001,EMPLOYED,EMERSYN PARKER,CO-FOUNDERR,Business & Management,R 40 001- R 50 000,Private Sector,Somewhat related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16003,2017,TLBMAN001,EMPLOYED,BROLL PROPERTY GROUP,ESTATES MANAGER,Construction & Property Management,R 20 001- R 30 000,Private Sector,Somewhat related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16004,2017,LSSNIC002,EMPLOYED,NESSAL,OWNER,"IT, Telecoms & Information Services",Ad-Hoc (varies),Private Sector,Somewhat related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16005,2017,GRSJES003,EMPLOYED,PWC,TRAINEE ACCOUNTANT,Business & Management,R 12 001- R 15 000,Private Sector,Somewhat related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16006,2017,WLMMIC008,EMPLOYED,MAKERERE UNIVERSITY,LECTURER,Education,R 30 001- R 40 000,"Education, Government",Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16007,2017,WHNKUD001,EMPLOYED,SANCTIONS PAYMENT SOLUTIONS,ASSOCIATE SOFTWARE ENGINEER,"IT, Telecoms & Information Services",R 20 001- R 30 000,Private Sector,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16008,2017,CHVJOS092,EMPLOYED,AFRINIC,RESEARCH ENGINEER,"IT, Telecoms & Information Services",R 40 001- R 50 000,Private Sector,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16009,2013,FLMCAM001,SEEKING STUDIES,BIRDING AFRICA,INTERNSHIP,NaN,< R 5000,Private Sector,Somewhat related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16010,2014,GRDGER001,SEEKING STUDIES,Mothers Unite,DIRECTOR,NaN,< R 5000,NGO/ Civil organisation,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16011,2014,TDSLEV001,GAP YEAR,DOH,OT COMM SERVE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16012,2014,JSPRAG001,OTHER,VICTORIA HOSPITAL,MEDICAL INTERN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16013,2014,PTRCAT002,NOT DECIDED,WCED,TEACHER,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16014,2014,DVXMIK001,SEEKING STUDIES,Darul Arqam HIGH SCHOOL,TEACHER,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16015,2014,MKNPAL006,SEEKING STUDIES,KORBITEC,SOFTWARE ENGINEER,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16016,2014,HLHMPH003,SEEKING EMPLOYMENT,DSD Khayelitsha Office,SOCIAL WORKER,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16017,2014,NTSBOM001,STUDYING,DOH,DOCTOR (INTERN),NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16018,2014,TLCKAV001,STUDYING,SELF,UX GRADUATE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16019,2015,LGRZAI002,STUDYING,CSUR,RESEARCH INTERN,Social & Community Services,< R 5000,NGO/ Civil organisation,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16020,2015,MMBTAN002,STUDYING,Age of the Artist,ACTOR,Art & Design,Ad-Hoc (varies),Other,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16021,2015,MHLNON031,SEEKING EMPLOYMENT,Department of social development,SOCIAL WORK SUPERVISOR,Social & Community Services,> R 20 000,Government,Directly Related,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16022 entries, 0 to 16021
Data columns (total 26 columns):
YEAR                                       16022 non-null int64
CAMPUSID                                   16022 non-null object
MAINACTIVITY                               16022 non-null object
EMPLOYER                                   9065 non-null object
JOBTITLE                                   9021 non-null object
INDUSTRY                                   4007 non-null object
SALARY                                     6927 non-null object
SECTOR                                     7151 non-null object
EMPLOYMENT RELATED TO STUDIES              7159 non-null object
StudentData.Sex                            14799 non-null object
StudentData.Population Group               14782 non-null object
StudentData.Citizenship Residency          14790 non-null object
StudentData.International Or SA            14792 non-null object
StudentData.Home Street Country            14761 non-null object
StudentData.Confer Year                    14799 non-null float64
StudentData.History Level Of Study         14799 non-null object
StudentData.Degree Academic Career Code    14799 non-null object
StudentData.Degree Academic Career         14799 non-null object
StudentData.Degree Faculty Code            14798 non-null object
StudentData.Degree Faculty                 14798 non-null object
StudentData.Awarded Degree Code            14798 non-null object
StudentData.Awarded Degree                 14798 non-null object
StudentData.Academic Program Code          14799 non-null object
StudentData.Academic Program               14799 non-null object
StudentData.Academic Plan 1                14789 non-null object
StudentData.Academic Plan 1 Code           14789 non-null object
dtypes: float64(1), int64(1), object(24)
memory usage: 3.2+ MB

In [4]:
df['MAINACTIVITY'].value_counts()

EMPLOYED              7338
STUDYING              4208
SEEKING EMPLOYMENT    2324
SEEKING STUDIES       1443
GAP YEAR               270
NOT DECIDED            198
NOT AVAILABLE          133
OTHER                  108
Name: MAINACTIVITY, dtype: int64

In [5]:
df['EMPLOYER'].value_counts()

Department of Health                   473
SELF                                   324
WCED                                   214
DOH                                    203
DELOITTE                               181
UCT                                    166
KPMG                                   137
University of Cape Town                125
PWC                                    122
Self-employed                          105
OLD MUTUAL                              98
ESKOM                                   90
INVESTEC                                67
Western Cape Education Department       67
SANLAM                                  55
ERNST & YOUNG                           47
STANDARD BANK                           46
ALLAN GRAY                              46
CITY OF CAPE TOWN                       39
SASOL                                   37
TRANSNET                                34
EY                                      30
ABSA                                    28
FNB                                     27
NEDBANK                                 26
CSIR                                    25
AURECON                                 24
Self employed                           24
SAOTA                                   23
BOWMAN GILFILLAN                        21
                                      ...
Engwelezane Hospital                     1
FAR EAST RAND HOSPITAL                   1
RED CROSS CHILDRENS HOSPITAL             1
IMBONO FJA ARCHITECTS                    1
BERLITZ VIRTUAL COLLEGE                  1
BEACON VIEW PRIMARY                      1
CONCEPT STUDIO                           1
UPSTREAMEDUCATION                        1
EKURHUENI HEALTH DISTRICT                1
PROF Z K MATTHEWS                        1
PLATES                                   1
Norton Rose Fullbright                   1
BUHLER                                   1
Clinkatell (Pty) Ltd                     1
SA DECOR                                 1
MOE                                      1
MONDELEZ                                 1
UNIVERSITY OF CAPE TOEN                  1
EDEN FORESTRY COMPANY LTD                1
STEINER STEUERBERATUNGSGES.MBH           1
PAM GOLDING PROPERTIES GAUTENG EAST      1
AGRICULTURE                              1
Government of Limpopo                    1
Lab 19 Digital                           1
Mark Saint POL                           1
CAREL SA                                 1
S4 Integration                           1
ANGLO GOLD ASHANTI                       1
SANTIWARE                                1
LEGAL AID                                1
Name: EMPLOYER, Length: 3614, dtype: int64

In [6]:
df['JOBTITLE'].value_counts()

TEACHER                                    445
DOCTOR                                     331
TRAINEE ACCOUNTANT                         295
CANDIDATE ATTORNEY                         200
INTERN                                     199
ANALYST                                    191
MEDICAL INTERN                             136
SOCIAL WORKER                              126
OCCUPATIONAL THERAPIST                     124
ENGINEER IN TRAINING                       122
LECTURER                                   120
PHYSIOTHERAPIST                            113
CONSULTANT                                  98
EDUCATOR                                    77
BUSINESS ANALYST                            73
CA TRAINEE                                  71
AUDIOLOGIST                                 65
ENGINEER                                    64
TRAINEE                                     64
TUTOR                                       63
AUDIT TRAINEE                               62
DEVELOPER                                   56
PROFESSIONAL NURSE                          56
RESEARCHER                                  55
DIRECTOR                                    54
ACCOUNTANT                                  54
ARTICLE CLERK                               51
PROJECT MANAGER                             50
SOFTWARE DEVELOPER                          50
GRADUATE ENGINEER                           48
                                          ...
AUDIY CLERK                                  1
QUANTITATIVE MODELLING GRADUATE TRAINEE      1
SENIOR ECONIMIC PLANNER                      1
AUDIO ENGINEER AND SOUND DESIGNER            1
AUDILOGIST                                   1
FASHION DESIGN INTERN                        1
INTERN (GRADUATE TRAINEE)                    1
LECTURER AND RESEARCHER                      1
PROMOTIONS SUPERVISOR                        1
SPECIALIST ANATOMICAL PATHOLOGIST            1
PRODUCTION ASSISTANT INTERN                  1
SERVICE PROGRAMMING DIRECTOR                 1
TECHNOLOGY NURSE                             1
ASSISTANTDIRECTOR                            1
CELLO TEACHER                                1
SUPERINTENDENT PROCESSING/METALLURGY         1
SENIOR INNOVATION ASISSTANT                  1
EVRG                                         1
SENIOR WEB DEVELOPER                         1
MERCHANDISE PLANNER TRAINEE                  1
POSTDOCTORAL                                 1
CHIROPRACTOR                                 1
RADIO DJ                                     1
ESTATES MANAGER                              1
HEAD OF BUSINESS DVELOPMENT                  1
RETAIL LEASING ASSISTANT                     1
ENGLISH CONTENT WRITER                       1
MEDICAL PROFESSIONAL                         1
OCEANOGRAPHER                                1
ANALYST OF DERIVATIVES SETTLEMENTS           1
Name: JOBTITLE, Length: 2396, dtype: int64

In [7]:
df['SALARY'].value_counts()

> R 20 000               2118
R 15 001- R 20 000       1204
R 12 001- R 15 000        769
R 9001- R 12 000          629
< R 5000                  427
R 20 001- R 30 000        363
R 5001- R 7000            345
R 7001- R 9000            302
Ad-Hoc (varies)           253
R 30 001- R 40 000        208
> R 50 000                161
R 40 001- R 50 000        110
> R 900 000                 9
R 700 001 - R 800 000       7
R 400 001 - R 500 000       5
R 600 001 - R 700 000       5
R 800 001 - R 900 000       3
R 300 001 - R 400 000       3
R 500 001 - R 600 000       3
R 200 001 - R 300 000       2
R 100 001 - R 200 000       1
Name: SALARY, dtype: int64

In [8]:
df['INDUSTRY'].value_counts()

Health Care                            673
Finance, Insurance, Actuarial Work     529
Education                              430
Engineering or Industrial              312
OTHER                                  262
IT, Telecoms & Information Services    261
Business & Management                  256
Legal                                  181
Commercial & Retail                    180
Advertising, Marketing, PR             162
Construction & Property Management     147
Art & Design                           115
Public Sector                           88
Social & Community Services             85
Utilities & Energy                      62
Investment Banking                      55
Manufacturing                           54
Hotel & Leisure/Entertainment           44
Agriculture, Fishing & Forestry         43
Mining                                  41
Transport & Related Services            27
Name: INDUSTRY, dtype: int64

In [9]:
df['EMPLOYMENT RELATED TO STUDIES'].value_counts()

Directly Related    5224
Somewhat related    1429
Not related          460
Unsure                46
Name: EMPLOYMENT RELATED TO STUDIES, dtype: int64

In [10]:
df['StudentData.Sex'].value_counts()

Female        8553
Male          6243
Undeclared       2
Trans            1
Name: StudentData.Sex, dtype: int64

In [11]:
df['StudentData.Degree Academic Career'].value_counts()

Undergraduate                     7866
Honours                           1986
Masters                           1724
Postgraduate Diploma              1466
Undergrad Health Sciences          996
Doctoral                           485
GSB (Postgraduate Programmes)      271
GSB (Undergraduate Programmes)       5
Name: StudentData.Degree Academic Career, dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16022 entries, 0 to 16021
Data columns (total 26 columns):
YEAR                                       16022 non-null int64
CAMPUSID                                   16022 non-null object
MAINACTIVITY                               16022 non-null object
EMPLOYER                                   9065 non-null object
JOBTITLE                                   9021 non-null object
INDUSTRY                                   4007 non-null object
SALARY                                     6927 non-null object
SECTOR                                     7151 non-null object
EMPLOYMENT RELATED TO STUDIES              7159 non-null object
StudentData.Sex                            14799 non-null object
StudentData.Population Group               14782 non-null object
StudentData.Citizenship Residency          14790 non-null object
StudentData.International Or SA            14792 non-null object
StudentData.Home Street Country            14761 non-null object
StudentData.Confer Year                    14799 non-null float64
StudentData.History Level Of Study         14799 non-null object
StudentData.Degree Academic Career Code    14799 non-null object
StudentData.Degree Academic Career         14799 non-null object
StudentData.Degree Faculty Code            14798 non-null object
StudentData.Degree Faculty                 14798 non-null object
StudentData.Awarded Degree Code            14798 non-null object
StudentData.Awarded Degree                 14798 non-null object
StudentData.Academic Program Code          14799 non-null object
StudentData.Academic Program               14799 non-null object
StudentData.Academic Plan 1                14789 non-null object
StudentData.Academic Plan 1 Code           14789 non-null object
dtypes: float64(1), int64(1), object(24)
memory usage: 3.2+ MB

In [13]:
df['StudentData.Population Group'].value_counts()

White         5128
Black         3596
NA/Unknown    2634
Coloured      2179
Indian        1122
Chinese        123
Name: StudentData.Population Group, dtype: int64

In [14]:
df['StudentData.International Or SA'].value_counts()

South African    12770
International     2022
Name: StudentData.International Or SA, dtype: int64

# Data Cleaning
### cleaning variables that will be used to predict employment / seeking employment

# Predicting Employment

Predict EMPLOYED/SEEKING EMPLOYMENT based on sex, population group, intl or SA or home country, level of study or academic career code, awarded degree code or academic program code

In [37]:
df2=df[(df['MAINACTIVITY']=='EMPLOYED')|(df['MAINACTIVITY']=='SEEKING EMPLOYMENT')] #only look at employed or seeking employment, not those studying, seeking studies or gap years.
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9662 entries, 25 to 16021
Data columns (total 26 columns):
YEAR                                       9662 non-null int64
CAMPUSID                                   9662 non-null object
MAINACTIVITY                               9662 non-null object
EMPLOYER                                   7617 non-null object
JOBTITLE                                   7574 non-null object
INDUSTRY                                   3947 non-null object
SALARY                                     6725 non-null object
SECTOR                                     6920 non-null object
EMPLOYMENT RELATED TO STUDIES              6925 non-null object
StudentData.Sex                            9027 non-null object
StudentData.Population Group               9015 non-null object
StudentData.Citizenship Residency          9020 non-null object
StudentData.International Or SA            9021 non-null object
StudentData.Home Street Country            9000 non-null object
StudentData.Confer Year                    9027 non-null float64
StudentData.History Level Of Study         9027 non-null object
StudentData.Degree Academic Career Code    9027 non-null object
StudentData.Degree Academic Career         9027 non-null object
StudentData.Degree Faculty Code            9026 non-null object
StudentData.Degree Faculty                 9026 non-null object
StudentData.Awarded Degree Code            9026 non-null object
StudentData.Awarded Degree                 9026 non-null object
StudentData.Academic Program Code          9027 non-null object
StudentData.Academic Program               9027 non-null object
StudentData.Academic Plan 1                9019 non-null object
StudentData.Academic Plan 1 Code           9019 non-null object
dtypes: float64(1), int64(1), object(24)
memory usage: 2.0+ MB

In [40]:
df2=df2[['MAINACTIVITY','StudentData.Sex', 'StudentData.Population Group', 'StudentData.International Or SA','StudentData.History Level Of Study', 'StudentData.Awarded Degree Code']]
df2.dropna(inplace=True)

In [41]:
#create dummy variables for numerous categorical features
cat_feats = ['StudentData.Sex', 'StudentData.Population Group', 'StudentData.International Or SA','StudentData.History Level Of Study', 'StudentData.Awarded Degree Code']
final_data = pd.get_dummies(df2,columns=cat_feats,drop_first=True)

In [42]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9012 entries, 25 to 14797
Columns: 340 entries, MAINACTIVITY to StudentData.Awarded Degree Code_SM09
dtypes: object(1), uint8(339)
memory usage: 3.1+ MB

In [43]:
#train test split
from sklearn.model_selection import train_test_split
X = X = final_data.drop('MAINACTIVITY',axis=1)
y = final_data['MAINACTIVITY']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [44]:
#logistic regression model
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

C:\Users\Boris\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [45]:
predictions_log_model = logmodel.predict(X_test)

In [46]:
from sklearn.metrics import classification_report

In [47]:
print(classification_report(y_test,predictions_log_model))

                    precision    recall  f1-score   support

          EMPLOYED       0.79      0.94      0.86      2242
SEEKING EMPLOYMENT       0.58      0.23      0.33       732

          accuracy                           0.77      2974
         macro avg       0.68      0.59      0.60      2974
      weighted avg       0.74      0.77      0.73      2974